---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengym-data
spec:
  accessModes:
    # Requires a CSI driver supporting RWOP. RWO permits multiple pods on one node.
    - ReadWriteOncePod
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengym-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
